[MODFISTO-293] Delete temp transactions after a failure
folio-org/mod-finance-storage pull request #252
Opened 2022-04-11 18:04 UTC by damien-git

## Purpose
[MODFISTO-293](https://issues.folio.org/browse/MODFISTO-293) - Error All expected transactions already processed
When a single transaction fails in a set of transactions with a summary, the summary will never be able to finish successfully, and typically the calling process will give up on the whole operation. So temporary transactions have to be removed, otherwise they will be taken into account the next time a user tries using a transaction summary on the same order/invoice.

We assume one thing: that a calling process will not try to fix a transaction after an error and continue creating or updating transactions for a given summary. There is nothing like that in FOLIO, and it would be surprising even from an API-using external program.

Eventually we should use unique summary ids, and this fix would be obsolete. It is meant for Lotus and possibly Kiwi.

## Approach
Catch any error (including validation) in createTransaction and updateTransaction, and remove all temporary transactions before returning it.

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2022-04-11 18:10 UTC, damien-git commented
![Screenshot_20220411_132223](https://user-images.githubusercontent.com/7503971/162802642-b78a0708-0aa5-46b7-adb3-f44398ff4864.png)
![Screenshot_20220411_132915](https://user-images.githubusercontent.com/7503971/162802643-9d1c92d6-e92b-4012-bea2-4c564e353474.png)
failing tests were failing before

2022-04-12 05:04 UTC, AndreiMPV approved these changes

2022-04-12 08:10 UTC, AndreiMPV requested changes

2022-04-12 08:10 UTC, AndreiMPV commented on src/main/java/org/folio/service/transactions/AllOrNothingTransactionService.java
> +    return client.startTx()
No need transaction here

2022-04-12 08:26 UTC, AndreiMPV approved these changes

2022-04-12 08:54 UTC, merged